---

- name: R | APT key (CRAN)
  tags:
  - apt
  apt_key:
    keyserver: keys.gnupg.net
    id: "{{ cran_key }}"

- name: R | repository (CRAN)
  tags:
  - apt
  apt_repository:
    repo: "deb {{ cran_mirror }}/bin/linux/debian {{ ansible_distribution_release }}-{{ cran_ver }}/"
    filename: 'cran'

- name: R | Install packages
  tags:
  - package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - r-base
  - r-base-dev
  - libopenblas-base

# /usr/bin/Rscript -e 'install.packages("tidyverse", repos="http://cran.us.r-project.org")'

# chooseCRANmirror()
# install.packages("Matrix", "Rcpp", "RcppEigen")
