---

- name: NTP client | package
  tags:
  - package
  package:
    name: ntp
    state: present

- name: NTP client | config
  tags:
  - config
  copy:
    src: ntp.conf
    dest: /etc/
  notify: restart ntp

- name: NTP client | service
  tags:
  - service
  service:
    name: ntp
    state: started
    enabled: yes
