---

- name: Nginx | APT key
  tags:
  - apt
  apt_key:
    id: 7BD9BF62
    url: http://nginx.org/keys/nginx_signing.key

- name: Nginx | repository
  tags:
  - apt
  apt_repository:
    repo: 'deb http://nginx.org/packages/mainline/{{ ansible_distribution | lower }}/ {{ ansible_lsb.codename }} nginx'
    filename: 'nginx'

- name: Nginx | package
  tags:
  - package
  package:
    name: nginx
    state: latest

- name: Nginx | config dirs
  tags:
  - dir
  file:
    path: /etc/nginx/{{ item }}
    state: directory
    mode: 0750
  with_items:
  - conf.d
  - ssl
  - sites-available
  - sites-enabled

- name: Nginx | config
  tags:
  - config
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/"
  with_items:
  - nginx.conf
  - conf.d
  - ssl
  - sites-available
  notify: restart nginx

- name: Nginx | log archive dir
  tags:
  - dir
  file:
    path: /var/log/nginx/old
    state: directory
    owner: nginx
    group: adm
    mode: 0750

- name: Nginx | default site dir
  tags:
  - dir
  - site
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: 0750

- name: Nginx | default site index.html
  tags:
  - site
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    group: www-data
    mode: 0640
  notify: restart nginx

- name: Nginx | enable default site
  tags:
  - site
  file:
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
  with_items:
  - 0default

- name: Nginx | service
  tags:
  - service
  service:
    name: nginx
    state: started
    enabled: yes

