---

- name: Nginx | APT key
  tags:
  - apt
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key

- name: Nginx | repository
  tags:
  - apt
  apt_repository:
    repo: 'deb http://nginx.org/packages/mainline/debian/ jessie nginx'
    filename: 'nginx.list'

- name: Nginx | package
  tags:
  - package
  package:
    name: nginx
    state: latest

- name: Nginx | directories
  tags:
  - dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/nginx/ssl
  - /etc/nginx/sites-available
  - /etc/nginx/sites-enabled
  - /var/www/html

- name: Nginx | SSL certs
  tags:
  - config
  - crypt
  copy:
    src: "{{item}}"
    dest: /etc/nginx/ssl/
    mode: 0640
  with_items:
  - _dhparams.pem
  - _ssl.crt
  - _ssl.key
  notify: restart nginx

- name: Nginx | config
  tags:
  - config
  copy:
    src: "{{ item.src }}"
    dest: "/etc/nginx/{{ item.dest }}"
    mode: 0640
  with_items:
  - { src: nginx.conf, dest: "" }
  - { src: acme-redir, dest: "" }
  - { src: default.nginx, dest: "sites-available" }
  - conf.d
  notify: restart nginx

- name: Nginx | enable default site
  tags:
  - site
  file:
    src: /etc/nginx/sites-available/default.nginx
    dest: /etc/nginx/sites-enabled/0default
    state: link

- name: Nginx | default index.html
  tags:
  - site
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644
  notify: restart nginx

- name: Nginx | service
  tags:
  - service
  service:
    name: nginx
    state: started
    enabled: yes
