---
dependencies:
  - { role: sudo, tags: [sudo] }
  - { role: basepkgs, tags: [basepkgs] }
  - { role: ssh, tags: [ssh] }
  - { role: iptables, tags: [iptables] }
  - { role: bash, tags: [bash] }
  - { role: msmtp, tags: [msmtp, mail] }
  - { role: rsyslog, tags: [rsyslog] }
  - { role: logrotate, tags: [logrotate] }
  - { role: tinc, tags: [tinc, vpn] }
  - { role: burp, tags: [burp, backup] }

