---
- name: SNMP remote monitoring
  become: true

  tasks:

  - name: Install SNMPd
    apt: pkg=snmpd state=present

  - name: SNMPd config
    template: src=snmpd.conf.j2 dest=/etc/snmp/snmpd.conf
    notify:
    - Restart SNMPd

  - name: SNMPd service
    service: name=snmpd state=started enabled=yes
