---
cloud_version: 11.0.1
cloud_db_version: 11.0.1.2
cloud_server: cloud.example.com
cloud_port: 443
cloud_www_dir: /var/www/nextcloud
cloud_data_dir: /var/lib/nextcloud
cloud_cache_dir: /var/cache/nginx

cloud_db: nextcloud
cloud_db_host: /var/run/postgresql
cloud_db_user: nextcloud
cloud_db_prefix: 'oc_'

cloud_pw: ''
cloud_secret: ''
cloud_id: ''
cloud_db_pw: ''
