stop_services: []

remove_pkgs:
- cron
- at
- apache2
- apache2-doc
- apache2-utils
- bind9
- bind9utils
- finger
- ftp
- lynx
- lynx-cur
- procmail
- screen
- tcpdump
- telnet
- samba
- samba-common
- rpcbind
- sasl2-bin
- xinetd
- update-inetd
- tcsh
- fetchmail
- w3m

install_pkgs:
- apt-transport-https
- systemd-cron
- locales
- git
- less
- vim
- htop
- iotop
- file
- bind9-host
- rsync
- python-apt
- aptitude
- unattended-upgrades
- policykit-1
