---

- name: systemd-networkd | disable stable interface names
  tags:
    - network
  copy:
    src: 99-default.link
    dest: /etc/systemd/network/
  notify: update initramfs

- name: systemd-networkd | service
  tags:
    - network
    - service
  service:
    name: systemd-networkd
    state: started
    enabled: yes
