---

- name: systemd-networkd | disable stable interface names
  tags:
    - network
  copy:
    src: 99-default.link
    dest: /etc/systemd/network/
  notify: update initramfs

- name: systemd-networkd | remove dhcp clients
  tags:
    - network
    - package
  package:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - isc-dhcp-common
    - isc-dhcp-client
    - dhcpcd5

- name: systemd-networkd | service
  tags:
    - network
    - service
  service:
    name: systemd-networkd
    state: started
    enabled: yes
