---

- name: rsyslog | packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
  - rsyslog
  - rsyslog-relp

- name: rsyslog | client config
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    mode: 0600
  notify: restart rsyslog

- name: rsyslog | server config
  copy:
    src: server.conf
    dest: /etc/rsyslog.conf
    mode: 0600
  notify: restart rsyslog

- name: rsyslog | service
  service:
    name: rsyslog
    state: started
    enabled: yes
