---

- name: rsyslog | packages
  tags:
  - package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - rsyslog
  - rsyslog-relp

- include_tasks: client.yml
  when: '"log" not in group_names'
- include_tasks: server.yml
  when: '"log" in group_names'

- name: rsyslog | service
  tags:
  - service
  service:
    name: rsyslog
    state: started
    enabled: yes
