---

- name: rsyslog | packages
  tags:
  - package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - rsyslog
  - rsyslog-relp

- name: rsyslog | client config
  tags:
  - config
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    mode: 0600
  notify: restart rsyslog

- name: rsyslog | server config
  tags:
  - config
  copy:
    src: server.conf
    dest: /etc/rsyslog.conf
    mode: 0600
  notify: restart rsyslog

- name: rsyslog | service
  tags:
  - service
  service:
    name: rsyslog
    state: started
    enabled: yes
