---
- name: Top-level Ansible playbook
  hosts: all
  roles:
    - common

  tasks:
    - group_by: key=os_{{ ansible_os_family }}

- include: plays/tmux.yml
- include: plays/dns.yml
- include: plays/www.yml
- include: plays/news.yml
- include: plays/cloud.yml
- include: plays/R.yml
