---
- name: Top-level Ansible playbook
  hosts: all
  roles:
    - common

  tasks:
    - group_by: key=os_{{ ansible_os_family }}

- include: backup.yml
- include: www.yml
- include: news.yml
- include: cloud.yml
