#! /usr/bin/env ansible-playbook
# Master playbook invoking role-specific plays
---
- import_playbook: plays/update.yml
- import_playbook: plays/linux.yml
- import_playbook: roles/wireguard/plays/main.yml
- import_playbook: roles/dnsmasq/plays/main.yml
- import_playbook: roles/tmux/plays/main.yml
- import_playbook: roles/burp-server/plays/main.yml
- import_playbook: roles/k3s/plays/main.yml
- import_playbook: roles/squid/plays/main.yml
- import_playbook: roles/nginx-site/plays/main.yml
- import_playbook: roles/ttrss/plays/main.yml
- import_playbook: roles/nextcloud/plays/main.yml
- import_playbook: roles/node-app/plays/main.yml
