---
- name: Top-level Ansible playbook
  hosts: all
  roles:
    - common

  tasks:
    - group_by: key=os_{{ ansible_distribution }}

- include: vpn.yml
- include: backup.yml
- include: www.yml
- include: news.yml
- include: cloud.yml
