---

- name: install aptitude
  tags:
  - package
  package:
    name: aptitude

- name: Upgrade packages (Debian)
  when: ansible_os_family == "Debian"
  tags:
  - package
  - update
  apt:
    autoclean: yes
    update_cache: yes
    cache_valid_time: 86400
    upgrade: full

- name: Upgrade packages (RedHat)
  when: ansible_os_family == "RedHat"
  tags:
  - package
  - update
  yum:
    update_cache: yes
    name: '*'
    state: latest
