---

- name: Upgrade packages (Debian)
  when: ansible_os_family == "Debian"
  tags:
    - package
    - update
  apt:
    autoclean: yes
    update_cache: yes
    cache_valid_time: 86400
    upgrade: dist
