---

- name: tinc VPN | check for existing key
  local_action:
    module: stat
    path: "{{ tinc_keystore }}/{{ inventory_hostname }}/pub.key"
  register: pubkey

- include_tasks: genkey.yml
  when: "not pubkey.stat.exists and not 'vpn' in group_names"

- name: tinc VPN | private key
  tags:
  - config
  - crypt
  copy:
    src: "keys/{{ inventory_hostname }}/{{ item }}.key"
    dest: "{{ tinc_dir }}/{{ item }}_key.priv"
    mode: 0400
  with_items:
    - rsa
    - ed25519
  notify: restart tinc

- name: tinc VPN | client public key
  tags:
    - config
    - crypt
  copy:
    src: "keys/{{ inventory_hostname }}/pub.key"
    dest: "{{ tinc_dir }}/hosts/{{ inventory_hostname }}"
    mode: 0640
  notify: restart tinc

