---

- name: tinc VPN | check for existing key
  local_action:
    module: stat
    path: "{{ tinc_keydir }}"
  register: keydir

- include_tasks: genkey.yml
  when: "not keydir.stat.exists and not 'vpn' in group_names"

- name: tinc VPN | private key
  tags:
    - config
    - crypt
  copy:
    src: "{{ tinc_keydir }}/{{ item }}_key.priv"
    dest: "{{ tinc_dir }}"
    mode: 0400
  with_items:
    - rsa
    - ed25519
  notify: restart tinc

- name: tinc VPN | client public key
  tags:
    - config
    - crypt
  template:
    src: "host.j2"
    dest: "{{ tinc_dir }}/hosts/{{ inventory_hostname }}"
    mode: 0640
  vars:
    tinc_ed25519_pub: "{{ lookup( 'file', tinc_keydir + '/ed25519_key.pub' ) }}"
    tinc_rsa_pub: "{{ lookup( 'file', tinc_keydir + '/rsa_key.pub' ) }}"
  notify: restart tinc

