---

- name: tinc VPN | check for existing key
  local_action:
    module: stat
    path: "{{ tinc_keystore }}/pub/_{{ inventory_hostname }}"
  register: pubkey

- include_tasks: genkey.yml
  when: "not pubkey.stat.exists and not 'vpn' in group_names"

- name: tinc VPN | private key
  tags:
  - config
  - crypt
  copy:
    src: "{{ item }}"
    dest: "{{ tinc_dir }}/{{ item | regex_replace('^.*/([^/]*)/_[^/]*$', '\\1') }}_key.priv"
    mode: 0400
  with_fileglob: 
    - "keys/rsa/_{{ inventory_hostname }}"
    - "keys/ed25519/_{{ inventory_hostname }}"
  notify: restart tinc

- name: tinc VPN | client public key
  tags:
    - config
    - crypt
  copy:
    src: "keys/pub/_{{ item }}"
    dest: "{{ tinc_dir }}/hosts/{{ item }}"
    mode: 0640
  with_items:
    - "{{ inventory_hostname }}"
  notify: restart tinc

