---
# Create tinc host key 

- name: tinc genkey | host dir in keystore
  become: false
  local_action: 
    module: file
    path: "{{ tinc_keydir }}"
    state: directory
    mode: 0400

- name: tinc genkey | new host keys
  become: false
  local_action: "command /usr/sbin/tinc --batch -c {{ tinc_keydir }} generate-keys 4096"

- name: tinc genkey | push host public key to VPN servers
  template:
    src: host.j2
    dest: "{{ tinc_dir }}/hosts/{{ inventory_hostname }}"
  delegate_to: "{{ item }}"
  vars:
    tinc_addresses: "{{ lookup( 'file', tinc_keydir + '/addresses.yml' ) | from_yaml }}"
    tinc_subnets: "{{ lookup( 'file', tinc_keydir + '/subnets.yml' ) | from_yaml }}"
    tinc_ed25519_pub: "{{ lookup( 'file', tinc_keydir + '/ed25519_key.pub' ) }}"
    tinc_rsa_pub: "{{ lookup( 'file', tinc_keydir + '/rsa_key.pub' ) }}"
    ansible_port: "{{ hostvars[item]['ansible_port'] }}"
  with_items: "{{ groups['vpn'] }}"

