---

- name: tinc genkey | check for existing key
  local_action:
    module: stat
    path: "{{ tinc_keystore }}/pub/_{{ inventory_hostname }}"
  register: pubkey

- include_tasks: genkey.yml
  when: not pubkey.stat.exists

- include_tasks: server.yml
  when: '"vpn" in group_names'

- import_tasks: common.yml
