---

- name: tinc VPN server | all client pubkeys
  tags:
    - config
    - crypt
  template:
    src: host.j2
    dest: "{{ tinc_dir }}/hosts/{{ item }}"
    mode: 0640
  vars:
    tinc_addresses:   "{{ hostvars[item]['tinc_addresses']   }}"
    tinc_subnets:     "{{ hostvars[item]['tinc_subnets']     }}"
    tinc_ed25519_pub: "{{ hostvars[item]['tinc_ed25519_pub'] }}"
    tinc_rsa_pub:     "{{ hostvars[item]['tinc_rsa_pub']     }}"
  with: "{{ groups['all'] | difference(groups['vpn']) }}"

- name: tinc VPN server | private key
  tags:
    - config
    - crypt
  copy:
    src: "{{ tinc_keydir }}/{{ item }}_key.priv"
    dest: "{{ tinc_dir }}"
    mode: 0400
  with_items: 
    - rsa
    - ed25519
  notify: restart tinc

