---

- name: tinc VPN | public keys
  copy:
    src: ".private/hosts/{{ item }}"
    dest: "/etc/tinc/{{ tinc_name }}/hosts/"
    mode: 0640
  with_items:
  - tinc1
  - tinc2
  - "{{ ansible_hostname }}"
  notify: restart tinc

