---

- name: tinc VPN server | all public keys
  tags:
    - config
    - crypt
  copy:
    src: "keys/{{ item.path }}"
    dest: "{{ tinc_dir }}/hosts/{{ item.path | dirname | regex_replace('^.*/([^/]+)$', '\\1') }}"
    mode: 0640
  with_filetree: keys
  when: item.path | basename == 'pub.key'

- name: tinc VPN server | private key
  tags:
  - config
  - crypt
  copy:
    src: "keys/{{ cname }}/{{ item }}.key"
    dest: "{{ tinc_dir }}/{{ item }}_key.priv"
    mode: 0400
  with_items: 
    - rsa
    - ed25519
  notify: restart tinc

