---

- name: tinc VPN server | all public keys
  tags:
    - config
    - crypt
  template:
    src: host.j2
    dest: "{{ tinc_dir }}/hosts/{{ item }}"
    mode: 0640
  vars:
    tinc_addresses: "{{ lookup( 'file', tinc_keystore + '/' + item + '/addresses.yml' ) | from_yaml }}"
    tinc_subnets: "{{ lookup( 'file', tinc_keystore + '/' + item + '/subnets.yml' ) | from_yaml }}"
    tinc_ed25519_pub: "{{ lookup( 'file', tinc_keystore + '/' + item + '/ed25519_key.pub' ) }}"
    tinc_rsa_pub: "{{ lookup( 'file', tinc_keystore + '/' + item + '/rsa_key.pub' ) }}"
  with_items: "{{ lookup( 'fileglob', tinc_keystore ) }}"

- name: tinc VPN server | private key
  tags:
    - config
    - crypt
  copy:
    src: "{{ tinc_keystore }}/{{ tinc_hostname }}/{{ item }}_key.priv"
    dest: "{{ tinc_dir }}"
    mode: 0400
  with_items: 
    - rsa
    - ed25519
  notify: restart tinc

