---

- name: tinc VPN server | all public keys
  tags:
  - config
  - crypt
  copy:
    src: .private/hosts
    dest: "/etc/tinc/{{ tinc_net }}/hosts/{{ item | regex_replace('^_') }}"
    mode: 0640
    with_fileglob:
      - "pub/_*"

