---
- name: tinc VPN client (Windows)
  hosts: os_Windows

## TODO: Merge this into regular config, using group vars to set config dir and tinc.conf
# install new TAP device
# run "tincd -n ho" as admin and it will auto-install as service

  tasks:

  - name: tinc directories
    file: path={{item}} state=directory
    with_items:
    - /etc/tinc/ho/hosts

  - name: tinc config
    template: src=tinc-win.conf dest=/etc/tinc/ho/tinc.conf mode=0644
    notify:
      - restart tinc

  - name: tinc client key
    copy: src=.private/keys/{{ansible_hostname}}.priv dest=/etc/tinc/ho/rsa_key.priv mode=0400
    notify:
      - restart tinc

  - name: tinc public keys
    copy: src=.private/hosts/{{item}} dest=/etc/tinc/ho/hosts/ mode=0644
    with_items:
    - tinc1
    - tinc2
    - "{{ ansible_hostname }}"
    notify:
      - restart tinc

  - name: tinc service
    service: name=tinc state=started enabled=yes
