#! /bin/bash
## Check actual free memory on OpenVZ container

warn=90 # percent
crit=98

beanct=/proc/user_beancounters
AWK=/usr/bin/awk

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION="1"

. $PROGPATH/utils.sh

print_usage() {
        echo "Usage: $PROGNAME [-w warn_pct] [-c crit_pct]"
}

print_help() {
        print_revision $PROGNAME $REVISION
        echo ""
        print_usage
        echo ""
        echo "This plugin checks free memory on an OpenVZ container."
        echo ""
        support
        exit 0
}

while test -n "$1"; do
        case "$1" in
                --help|-h)
                        print_help
                        exit 0
                        ;;
                --version|-V)
                        print_revision $PROGNAME $REVISION
                        exit 0
                        ;;
                -w)
                        warn=$2
                        shift
                        ;;
                -c)
                        crit=$2
                        shift
                        ;;
                *)
                        break
                        ;;
        esac
done

if test ! -r "$beanct"; then
        echo "$beanct not found: not on OpenVZ?"
        exit -1
fi

usedKB=`$AWK '/privvmpages/ {print $2*4}' $beanct`
guarKB=`$AWK '/vmguarpages/ {print $4*4}' $beanct`
 maxKB=`$AWK '/privvmpages/ {print $4*4}' $beanct`
mempct=$[ 100 * usedKB / guarKB ]

info=`printf "Mem used %2.1f%% ( %d / %d | %d)" $mempct $usedKB $guarKB $maxKB`

if test "$mempct" -gt "$crit"; then
        echo "CRITICAL: $info"
        exit 2
elif test "$mempct" -gt "$warn"; then
        echo "WARNING: $info"
        exit 1
else
        echo "OK: $info"
        exit 0
fi
