---

- name: Logrotate | config
  copy:
    src: logrotate.conf
    dest: /etc/
    mode: 0644

- name: Logrotate | storage dir for old logs
  file:
    path: /var/log/old
    owner: root
    group: adm
    mode: 0770

- name: Logrotate | package
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
  - logrotate
  - cron
