---

- name: Logrotate | package
  tags:
  - package
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - logrotate

- name: Logrotate | config
  tags:
  - config
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf

- name: Logrotate | log archive dir
  tags:
  - dir
  file:
    path: /var/log/old
    state: directory
    owner: root
    group: adm
    mode: 0770
