---
- name: Nagios Remote Plugin Executor
  become: true

  tasks:

  - name: Nagios NRPE agent packages
    apt: pkg={{item}} state=present
    with_items:
    - nagios-nrpe-server
    - nagios-plugins-basic

  - name: Nagios NRPE initscript
    copy: src=nrpe dest=/etc/init.d/nrpe mode=0755
    notify:
    - Restart NRPE

  - name: Nagios NRPE initscript config
    copy: src=default_nrpe dest=/etc/default/nrpe
    notify:
    - Restart NRPE

  - name: Nagios NRPE config
    template: nrpe_local.cfg.j2 dest=/etc/nagios/nrpe_local.cfg
    notify:
    - Restart NRPE

  - name: NRPE custom plugins
    copy: src={{item}} dest=/usr/lib/nagios/plugins/ mode=0755
    with_items:
    - check_mem.pl
    - check_vzmem
    notify:
    - Restart NRPE

  - name: Nagios NRPE service
    service: name=nrpe state=started enabled=yes
