---
# curl -sL https://deb.nodesource.com/setup_4.x | /bin/bash
- name: Node.js
  become: true

  tasks:

  - name: NodeSource GPG key
    apt_key: url='https://deb.nodesource.com/gpgkey/nodesource.gpg.key'

  - name: Node.js: APT repository, v4.x
    apt_repository: repo='deb https://deb.nodesource.com/node_4.x jessie main' filename='nodejs'

  - name: Node.js: install packages
    apt: pkg=npm state=latest install_recommends=no

  - name: Node.js: NPM packages
    npm: name={{ item }}
    with_items:
    - grunt-cli
    - bower
    - yo

  - name: Node.js: nginx config
    copy: src=nodejs dest=/etc/nginx/sites-available/

  - name: Node.js: enable nginx host
    file: src=/etc/nginx/sites-available/nodejs dest=/etc/nginx/sites-enabled/nodejs state=link

  - name: Node.js: directories
    file: path=/var/www/node state=directory owner=www-data group=www-data mode=0750
