---

- name: nodejs | APT key
  tags:
    - apt
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: nodejs | repository
  tags:
    - apt
  apt_repository:
    repo: "deb https://deb.nodesource.com/{{ node_ver }} {{ ansible_distribution_release }} main"
    filename: 'nodejs'

- name: nodejs | package
  tags:
    - package
  package:
    name: "nodejs"
    state: latest
