---

- name: nodejs | APT key
  tags:
    - apt
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: nodejs | repository
  tags:
    - apt
  apt_repository:
    repo: "deb https://deb.nodesource.com/{{ node_ver }} {{ ansible_distribution_release }} main"
    filename: nodejs
    update_cache: yes

- name: nodejs | package
  tags:
    - package
  package:
    name: nodejs
    state: latest

- name: nodejs | update npm
  tags:
    - package
  npm:
    name: npm
    global: yes
    state: latest

