---
- name: ownCloud file sync server
  hosts: cloud
  become: true
  gather_facts: no

  tasks:

  - name: ownCloud GPG key
    apt_key: url='https://download.owncloud.org/download/repositories/stable/Debian_8.0/Release.key' validate_certs=no

  - name: ownCloud repository
    apt_repository: repo='deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /' # filename='owncloud'

  - name: ownCloud package
    apt: pkg=owncloud state=latest

  - name: ownCloud config.php
    copy: src=files/.private/config.php dest=/var/www/owncloud/config/ owner=www-data group=www-data mode=0640

  - name: ownCloud nginx config
    copy: src=files/owncloud dest=/etc/nginx/sites-available/

  - name: Enable ownCloud
    file: src=/etc/nginx/sites-available/owncloud dest=/etc/nginx/sites-enabled/owncloud state=link

  - name: ownCloud directories
    file: path={{item}} state=directory owner=www-data group=www-data mode=0750
    with_items:
    - /mnt/owncloud
    - /var/cache/nginx

- name: ownCloud DB
  hosts: cloud
  become: true
  become_user: postgres
  gather_facts: no

  vars:
  - dbname: owncloud
  - dbuser: owncloud

  vars_files:
  - .private/passwd.yml

  tasks:

  - name: Create ownCloud DB user
    action: postgresql_user name={{dbuser}} password={{owncloud_dbpw}} role_attr_flags=NOSUPERUSER,NOCREATEDB

  - name: Create ownCloud DB
    action: postgresql_db name={{dbname}} owner={{dbuser}}

