---

- name: OpenSSH | package
  tags:
  - package
  package:
    name: openssh-server
  notify: restart ssh

- name: OpenSSH | config
  tags:
  - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/ssh/{{ item }}"
  with_items:
  - sshd_config
  - ssh_config
  notify: restart ssh

- name: OpenSSH | service
  tags:
  - service
  service:
    name: ssh
    state: started
    enabled: yes

# ssh-keygen -G /tmp/moduli-cand -b 4096
# ssh-keygen -T /tmp/moduli -f /tmp/moduli-cand          # slow!
# mv /tmp/moduli /etc/ssh/moduli
# rm /etc/ssh/ssh_host_*_key
# ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key
# ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key

# ssh-keygen -t ed25519 -o -a 100
# ssh-keygen -t rsa -b 4096 -o -a 100
