---
# See: https://gitlab.paragon-es.de/ansible-roles/nextcloud/blob/master/tasks/install.yml

- name: nextCloud | dependencies
  tags:
  - package
  package:
    name: "{{ item }}"
    state: installed
  with_items:
  - php5-pgsql
  - php5-curl
  - php5-gd
  - php5-apcu
  - ffmpeg

- name: nextCloud | installation (git)
  tags:
  - package
  - git
  git:
    repo: 'https://github.com/nextcloud/server.git'
    dest: '{{ cloud_www_dir }}'
    version: 'v{{ cloud_version }}'
    depth: 1
    force: yes

- name: nextCloud | custom PHP config
  tags:
  - config
  copy:
    src: ".user.ini~"
    dest: "{{ cloud_www_dir }}/"
    owner: root
    group: www-data
    mode: 0640

- name: nextCloud | enable custom PHP config
  tags:
  - config
  lineinfile:
    path: /etc/php5/fpm/php.ini
    line: "user_ini.filename = '.user.ini~'"
    insertafter: "[PHP]"
    validate: /usr/sbin/php5-fpm -t
  notify: restart php-fpm

- name: nextCloud | config
  tags:
  - config
  template:
    src: config.php.j2
    dest: "{{ cloud_www_dir }}/config/config.php"

- name: nextCloud | mimetype config
  tags:
  - config
  copy:
    src: "{{ item }}"
    dest: "{{ cloud_www_dir }}/config/"
  with_items:
  - mimetypemapping.json
  - mimetypealiases.json

- name: nextCloud | secure file perms
  tags:
  - permissions
  file:
    path: "{{ cloud_www_dir }}"
    owner: root
    group: www-data
    mode: 'g-w,o='
    recurse: yes

- name: nextCloud | allow dir perms
  tags:
  - permissions
  file:
    path: "{{ cloud_www_dir }}/{{ item }}"
    owner: www-data
    group: www-data
    mode: 'u+rw'
    recurse: yes
  with_items:
  - apps
  - assets
  - config
  - themes
  - updater

- name: nextCloud | allow file perms
  tags:
  - permissions
  file:
    path: "{{ cloud_www_dir }}/{{ item }}"
    owner: www-data
    group: www-data
    mode: 'u+rw'
  with_items:
  - core/js/mimetypelist.js

- name: nextCloud | data directories
  tags:
  - dir
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0750
  with_items:
  - "{{ cloud_data_dir }}"
  - "{{ cloud_cache_dir }}"

- name: nextCloud | cron
  tags:
  - cron
  cron:
    name: 'nextCloud cron'
    cron_file: nextcloud
    minute: '4-49/15'
    user: www-data
    job: 'php {{ cloud_www_dir }}/cron.php 2>&- >&-'

- name: nextCloud | thumbnail cron
  tags:
  - cron
  cron:
    name: 'nextCloud thumbnail cron'
    cron_file: nextcloud_thumbs
    minute: 12
    hour: '0-23/6'
    user: www-data
    job: 'php {{ cloud_www_dir }}/occ preview:pre-generate 2>&- >&-'

- name: nextCloud | nginx config
  tags:
  - config
  - site
  template:
    src: "{{ item }}.nginx.j2"
    dest: /etc/nginx/sites-available/{{ item }}
  with_items:
  - nextcloud

- name: nextCloud | nginx site enabled
  tags:
  - site
  file:
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
  with_items:
  - nextcloud

- name: nextCloud | DB user
  tags:
  - db
  become_user: postgres
  postgresql_user:
    name: "{{ cloud_db_user }}"
    password: "{{ cloud_db_pw }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: nextCloud | DB
  tags:
  - db
  become_user: postgres
  postgresql_db:
    name: "{{ cloud_db }}"
    owner: "{{ cloud_db_user }}"

