---

- name: distcc | packages
  tags:
    - package
  package:
    name: "{{ item }}"
  with_items:
    - distcc-pump
  notify: restart distcc

- name: distcc | config
  tags:
    - config
  template:
    src: distcc.j2
    dest: /etc/default/distcc
  notify: restart distcc

- name: distcc | service
  tags:
    - service
  service:
    name: distcc
    state: started
    enabled: yes
