---
- name: network block device | packages
  tags:
  - package
  package:
   name: "{{ item }}"
   state: latest
  notify: restart xnbd
  with_items:
  - xnbd-server

- name: network block device | service
  tags:
  - service
  service:
    name: xnbd-common
    enabled: yes
