---

# Create 200GB image (cannot be sparse file)
# ionice -c 3 dd if=/dev/zero of=/srv/nbd0.img bs=1M count=200K

- name: network block device | packages
  tags:
  - package
  package:
   name: "{{ item }}"
   state: latest
  notify: restart xnbd
  with_items:
  - xnbd-server

- name: network block device | service
  tags:
  - service
  service:
    name: xnbd-common
    enabled: yes

- name: network block device (server) | config
  tags:
  - config
  template:
    src: server.conf.j2
    dest: /etc/xnbd.conf
  notify: restart xnbd
