---

- name: restart journald
  service:
    name: systemd-journald
    state: restarted

- name: restart journal-upload
  service:
    name: systemd-journal-upload
    state: restarted

- name: restart journal-remote
  service:
    name: systemd-journal-remote.socket
    state: restarted
