---

- name: restart journal
  service:
    name: systemd-journald
    status: restarted

- name: restart journal-upload
  service:
    name: systemd-journal-upload
    status: restarted

- name: restart journal-remote
  service:
    name: systemd-journal-remote
    status: restarted
