---

- name: git server | packages
  tags:
    - package
  package:
    name: "{{ item }}"
  with_items:
  - git

- name: git server | git user
  tags:
    - user
  user:
    name: "{{ git_user }}"
    shell: /usr/bin/git-shell

- name: git server | SSH keys
  tags:
    - ssh
  authorized_key:
    user: "{{ git_user }}"
    key: "{{ ssh_authorized_keys }}"
    exclusive: yes

- name: git server | repos
  tags:
    - git
  git:
    repo: "{{ item }}"
    dest: "/home/{{ git_user }}/{{ item | basename }}"
    bare: yes
  with_items: "{{ git_repos }}"

- name: git server | permissions
  file:
    path: "/home/{{ git_user }}"
    recurse: yes
    owner: "{{ git_user }}"
    group: "{{ git_user }}"
    mode: o=
