---
- name: "burp: backup client"
  hosts: all
  become: true

  vars_files:
  - .private/passwd.yml

  tasks:

  - name: "burp: directories"
    file: path={{item}} state=directory mode=0750
    with_items:
    - /etc/burp
    - /etc/burp/keys
    - /etc/burp/upgrade

  - name: "burp: executables"
    copy: src=files/sbin/{{item}} dest=/usr/sbin/ mode=0755
    with_items:
    - burp
    - burp_ca

  - name: "burp: config"
    template: src=files/burp.conf dest=/etc/burp/

  - name: "burp: dependencies"
    apt: pkg=librsync-dev
