---
- name: "Burp: backup server"
  hosts: backup-server
  become: yes

  tasks:

  - name: "Burp: server config"
    copy: src=files/server.conf dest=/etc/burp/ mode=0640

  - name: "Burp: autoupgrade scripts"
    copy: src=files/upgrade dest=/etc/burp/upgrade/server/

  - name: "burp: DH params"
    copy: src=files/.private/dhfile.pem dest=/etc/burp/keys/

  # Restore /etc/burp/CA/ dir from backups

