#! /bin/sh
## /etc/tinc/ho/tinc-up
## {{ansible_managed}}
## Link configuration once tinc VPN connection has been established

ip=/sbin/ip
dhcp=/sbin/dhcpcd

$ip link set $INTERFACE up

$dhcp -L $INTERFACE &
