---

- name: sudo | packages
  tags:
  - package
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - sudo

- name: sudo | user
  tags:
  - user
  user:
    name: "{{ ansible_user }}"
    groups:
    - sudo
    - adm

- name: sudo | SSH keys
  tags:
  - ssh
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  with_item: "{{ ssh_authorized_keys }}"
