---

- name: sudo | packages
  tags:
  - package
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - sudo

- name: sudo | group
  tags:
  - group
  group:
    name: "{{ item }}"
    state: present
  with_items:
  - sudo
  - adm

- name: sudo | /etc/sudoers
  tags:
  - config
  lineinfile:
    dest: /etc/sudoers
    regexp: '^%sudo'
    line: "%sudo   ALL=(ALL:ALL) NOPASSWD: ALL"
    state: present

- name: sudo | user
  tags:
  - user
  user:
    name: "{{ sudo_user }}"
    groups: "sudo,adm"
    shell: /bin/bash

- name: sudo | revoke SSH keys
  tags:
  - ssh
  authorized_key:
    user: "{{ sudo_user }}"
    key: "{{ item }}"
    state: absent
  with_items: "{{ ssh_revoked_keys }}"

- name: sudo | SSH keys
  tags:
  - ssh
  authorized_key:
    user: "{{ sudo_user }}"
    key: "{{ item }}"
  with_items: "{{ ssh_authorized_keys }}"
