---

- name: set random root password
  tags:
    - password
  user:
    name: root
    password: "{{ lookup('password', pw_store + '/' + inventory_hostname + ' encrypt=no length=32') | password_hash('sha512') }}"
