---

- name: Stop unneeded services
  tags:
  - service
  service:
    name: "{{item}}"
    state: stopped
  with_items: "{{stop_services}}"

- name: Clean unneeded packages
  tags:
  - pkgs
  package:
    name: "{{item}}"
    state: absent
  with_items: "{{remove_pkgs}}"

- name: Install packages
  tags:
  - pkgs
  package:
    name: "{{item}}"
    state: latest
  with_items: "{{install_pkgs}}"

