---
- name: Standard packages
  hosts: os_Debian
  become: true
  gather_facts: false

  tasks:

  - name: Stop unneeded services
    service: name={{item}} state=stopped
    with_items: "{{stop_services}}"

  - name: Clean unneeded packages
    apt: pkg={{item}} state=absent purge=yes install_recommends=no
    with_items: "{{remove_pkgs}}"

  - name: Update APT cache
    apt: update_cache=yes
    notify:
    - apt upgrade

  - name: Install packages
    apt: pkg={{item}} state=present install_recommends=no
    with_items: "{{install_pkgs}}"
