#! /usr/bin/env ansible-playbook
# Config ssh/sudo access so subsequent plays can run as usual
---

- name: access | config ansible access
  hosts: all
  vars:
    - ansible_user: root
    - ansible_port: 22
    - ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  roles:
    - { role: user, tags: [new,user] }
    - { role: sudo, tags: [new,sudo] }
    - { role: iptables, tags: [new,iptables] }
    - { role: ssh, tags: [new,ssh] }

