#! /usr/bin/env ansible-playbook
# Config ssh/sudo access so subsequent plays can run as usual
# Assumes ssh is listening on tcp/22 and root can login with password (-k)
---

- name: access | config ansible access
  hosts: all
  vars:
  - ansible_user: root
  - ansible_port: 22
  - ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  roles:
  - role: user
  - role: sudo
  - role: iptables
  - role: ssh

