---
# Playbook assigning role to inventory group
- name: common | Linux hosts
  hosts: linux
  roles:
    - { role: common, tags: [common] }
    - { role: sudo, tags: [sudo, login] }
    - { role: ssh, tags: [ssh, login] }
    - { role: basepkgs, tags: [basepkgs, apt] }
    - { role: msmtp, tags: [msmtp, mail] }
    - { role: tinc, tags: [tinc, vpn] }
    - { role: systemd-networkd, tags: [network, systemd] }
    - { role: systemd-resolved, tags: [resolver, systemd] }
    - { role: systemd-journald, tags: [log, journal, systemd] }
    - { role: rsyslog, tags: [rsyslog, log] }
    - { role: logrotate, tags: [logrotate, log] }
    - { role: bash, tags: [bash] }
    - { role: burp, tags: [burp, backup] }
    - { role: systemd-cron, tags: [cron, systemd] }
    - { role: systemd-timesyncd, tags: [timesync, systemd, ntp, time], when: ansible_virtualization_type != 'openvz' }
    - { role: iptables, tags: [iptables, firewall] }

