#! /usr/bin/env ansible-playbook
---
- name: Upgrade Debian release 
  hosts: debian
  tasks: 
  - name: Change release
    block:
    - name: Fetch list of sources
      find:
        path: /etc/apt
        pattern: '*.list'
        recurse: yes
        contains: '.*{{ release_old }}.*'
      register: sources_list
    - name: Update sources.list
      replace:
        path: '{{ item.path }}'
        regexp: '{{ release_old }}'
        replace: '{{ release_new }}'
      loop: "{{ sources_list.files }}"
    - name: Rename /updates to -security (bullseye)
      replace:
        path: /etc/apt/sources.list
        regexp: '{{ release_new }}/updates'
        replace: '{{ release_new }}-security'
    - name: Dist upgrade
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
    when: ansible_distribution_release == release_old 

