#! /usr/bin/env ansible-playbook
---
- name: Upgrade Debian release 
  hosts: linux
  tasks: 
    - include_tasks: tasks/update.yml
      when: ansible_distribution_release == release_old
    - include_tasks: tasks/dist-upgrade.yml
      when: ansible_distribution_release == release_old
