#! /usr/bin/env ansible-playbook
---
- name: Upgrade Debian release 
  hosts: linux
  tasks: 
  - name: Change release
    block:
    - name: Update sources.list
      replace:
        path: /etc/apt/sources.list
        regexp: '{{ release_old }}'
        replace: '{{ release_new }}'
    - name: Safe upgrade
      apt:
        update_cache: yes
        upgrade: safe
    - name: Dist upgrade
      apt:
        upgrade: dist
        autoremove: yes
    when: ansible_distribution_release == release_old and ansible_virtualization_type != "openvz"

