#! /usr/bin/env ansible-playbook
# Reset firewall rules
---

- name: iptables-flush
  hosts: linux
  pre_tasks:
    - import_tasks: ../roles/iptables/tasks/flush.yml
  roles:
    - { role: iptables, tags: [flush] }
    - { role: ssh, tags: [flush] }

