#! /usr/bin/env ansible-playbook
# Playbook assigning role to inventory group
---
- name: k3s | Kubernetes clusters
  hosts: k8s
  roles:
  - role: k3s
    tags: 
      - k3s
      - k8s
      - kubernetes

