#! /usr/bin/env ansible-playbook
# Playbook assigning role to inventory group
---

- name: linux | Basic setup for Linux hosts
  hosts: linux
  roles:
  - { role: common, tags: [common] }
  - { role: bash, tags: [bash] }
  - { role: sudo, tags: [sudo, login] }
  - { role: user, tags: [user, password, login] }
  - { role: iptables, tags: [iptables, firewall] }
  - { role: ssh, tags: [ssh, login] }
  - { role: basepkgs, tags: [basepkgs, apt] }
  - { role: msmtp, tags: [msmtp, mail] }
  - { role: systemd-networkd, tags: [network, systemd] }
  - { role: systemd-resolved, tags: [dns, resolver, systemd] }

