---
- name: main.yml | Common setup
  hosts: all
  roles:
  - common

- name: main.yml | TMux hosts
  hosts: tmux
  roles:
  - { role: tmux, tags: [tmux] }

- name: main.yml | VPN servers
  hosts: vpn
  roles:
  - { role: tinc, tags: [vpn] }

- name: main.yml | DNS servers
  hosts: dns
  roles:
  - { role: dnsmasq, tags: [dns] }

- name: main.yml | Web servers
  hosts: www
  roles:
  - { role: nginx, tags: [www] }

- name: main.yml | PHP-enabled webservers
  hosts: php
  roles:
  - { role: php, tags: [php] }

- name: main.yml | RSS news server
  hosts: news
  roles:
  - { role: ttrss, tags: [news] }

- name: main.yml | nextCloud servers
  hosts: cloud
  roles:
  - { role: nextcloud, tags: [cloud] }

- name: main.yml | R servers
  hosts: R
  roles:
  - { role: R, tags: [R] }
