---
- name: main.yml | Common setup
  hosts: linux
  roles:
    - common
  tasks:
    - include: tasks/update.yml

- name: main.yml | TMux hosts
  hosts: tmux
  roles:
  - { role: tmux, tags: [tmux] }

- name: main.yml | DNS servers
  hosts: dns
  roles:
  - { role: dnsmasq, tags: [dns, dnsmasq] }

- name: main.yml | NTP servers
  hosts: ntp
  roles:
  - { role: ntp, tags: [ntp] }

- name: main.yml | Web servers
  hosts: www
  roles:
  - { role: nginx, tags: [www, nginx] }

- name: main.yml | PHP app servers
  hosts: php
  roles:
  - { role: php, tags: [php] }

- name: main.yml | RSS news server
  hosts: news
  roles:
  - { role: ttrss, tags: [news, ttrss] }

- name: main.yml | nextCloud servers
  hosts: nextcloud
  roles:
  - { role: nextcloud, tags: [nextcloud] }

- name: main.yml | R servers
  hosts: R
  roles:
  - { role: R, tags: [R] }

- name: main.yml | xnbd 
  hosts: xnbd
  roles:
  - { role: xnbd, tags: [xnbd,nbd] }
