---
# Playbook invoking role-specific plays

- name: Update packages
  hosts: linux
  tasks:
    - import_tasks: tasks/update.yml

- import_playbook: "{{ item }}.yml"
  with_items:
    - common
    - dns
    - tmux
    - www
    - php
    - news
    - nextcloud
    - R
    - rstudio
    - node
    - xnbd
