#! /usr/bin/env ansible-playbook
# Playbook assigning role to inventory group
---
- name: nginx-site | static websites
  hosts: nginx-site
  roles:
  - role: nginx-site
    tags: 
      - www
      - nginx

