---
# Playbook assigning role to inventory group
- name: tinc
  tags:
    - vpn
    - tinc
  hosts: linux
  tasks:
    - include_tasks: tasks/tinc-role.yml
      with_items: "{{ tinc_networks }}"
      loop_control:
        loop_var: tinc_name
