#! /usr/bin/env ansible-playbook
# Loop over tinc networks
---

- name: tinc
  tags:
    - vpn
    - tinc
  hosts: linux
  tasks:
    - include_role:
        name: tinc
      loop: "{{ vars.keys() | select('search', '^tinc_subnet_') | map('regex_replace', '^tinc_subnet_') | list }}"
      loop_control:
        loop_var: tinc_network
