---
# Playbook assigning role to inventory group
- name: tinc
  hosts: linux
  tags:
    - vpn
    - tinc
  tasks:
    - include_vars: "{{ inventory_dir }}/.tinc/networks/{{ item }}.yml"
    - include_role: tinc
      with_items: tinc_networks
