#! /usr/bin/env ansible-playbook
---
- name: Update all packages
  hosts: linux
  gather_facts: false
  tasks: 
  - name: Upgrade packages (Debian)
    tags:
    - package
    - update
    apt:
      autoclean: yes
      update_cache: yes
      cache_valid_time: 86400
      upgrade: dist

