#! /usr/bin/env ansible-playbook
# Playbook assigning role to inventory group
---
- name: wireguard | VPN nodes
  hosts: wg
  roles:
    - role: wireguard
      when: ansible_virtualization_type != 'openvz'

