---
- name: TMux terminal multiplexer
  become: true
  gather_facts: false

  tasks:

  - name: TMux package
    apt: pkg=tmux state=present

  - name: TMux config
    copy: src=tmux.conf dest=/home/{{ansible_remote_user}}/.tmux.conf
