---
- name: OpenVPN client setup
  hosts: linux
  become: true

  tasks:

  - name: OpenVPN config directory
    action: file dest=/etc/openvpn state=directory

  - name: OpenVPN config
    action: template src=files/ho.conf dest=/etc/openvpn/ mode=0640

  - name: OpenVPN HMAC key
    action: copy src=files/hmac.key dest=/etc/openvpn/ mode=0400

  - name: OpenVPN client key
    action: copy src=files/keys/{{ansible_hostname}}.p12 dest=/etc/openvpn/ mode=0400

  - name: OpenVPN package
    action: apt pkg=openvpn state=present

  - name: OpenVPN service
    action: service name=openvpn state=started enabled=yes

  handlers:
  - name: Restart OpenVPN
    action: service name=openvpn state=restarted
