---

- name: common | copy misc config
  tags:
    - config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: htoprc, dest: /etc/ }
    - { src: 50unattended-upgrades, dest: /etc/apt/apt.conf.d/ }

- name: common | set hostname
  tags:
    - config
    - hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: common | set timezone
  tags:
    - config
    - time
  timezone:
    name: America/Vancouver

- name: common | generate locales
  tags:
    - config
    - locales
  locale_gen:
    name: en_US.UTF-8
