---

- name: msmtp | package
  tags:
    - package
  package:
    name: msmtp-mta

- name: msmtp | config
  tags:
    - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    group: www-data
    mode: 0640
  with_items:
    - msmtprc
    - aliases
  notify: restart msmtp

- name: msmtp | service
  tags:
    - service
  service:
    name: msmtp
    state: started
    enabled: yes
