---
- name: Tahoe-LAFS distributed object store
  hosts: tahoe
  become: true
  gather_facts: false

  tasks:

  - name: APT package priority
    action: copy src=files/priority dest=/etc/apt/preferences.d/priority
    notify:
    - apt upgrade

  - name: Wheezy (testing) repository
    action: copy src=files/wheezy.list dest=/etc/apt/sources.list.d/wheezy.list
    notify:
    - apt upgrade

  - name: FUSE package
    action: apt pkg=fuse-utils state=present

  - name: Tahoe-LAFS package
    action: apt pkg=tahoe-lafs state=present default_release=testing

  - name: Tahoe-LAFS config
    action: copy src=files/tahoe.conf dest=/etc/tahoe.conf
    notify:
    - Restart Tahoe-LAFS

  - name: Tahoe-LAFS service
    action: service name=tahoe-lafs state=started enabled=yes

  handlers:
  - name: apt upgrade
    action: command apt-get upgrade -qy
  - name: Restart Tahoe-LAFS
    action: service name=tahoe-lafs state=restarted
