---

- name: DNSMasq | package
  tags:
  - package
  package:
    name: "{{ item }}"
  with_items:
    - dnsmasq
    - dnsmasq-utils

- name: DNSmasq | config (template)
  tags:
  - config
  template:
    src : "{{ item  }}.j2"
    dest: "/etc/{{ item }}"
    owner: dnsmasq
    mode: 0440
  with_items:
    - dnsmasq.conf
    - dnsmasq.hosts
    - dnsmasq.servers
  notify: restart dnsmasq

- name: DNSmasq | config (copy)
  tags:
  - config
  copy:
    src : "{{ item.src  }}"
    dest: "{{ item.dest }}"
    owner: dnsmasq
    mode: 0440
  with_items: 
    - { src: dnsmasq.opts, dest: /etc/ }
    - { src: dnsmasq, dest: /etc/default/ }
  notify: reload dnsmasq

- name: DNSmasq | adblock list
  tags:
  - config
  get_url:
    url : "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts"
    dest: "/etc/adblock.hosts"
  notify: reload dnsmasq

- name: DNSMasq | service
  tags:
  - service
  service:
    name: dnsmasq
    state: started
    enabled: yes
