---

- name: DNSmasq | config
  tags:
  - config
  copy:
    src: "{{item}}"
    dest: /etc/
    owner: dnsmasq
    mode: 0440
  with_items: 
  - dnsmasq.conf
  - dnsmasq.opts
  - dnsmasq.hosts
  notify: restart dnsmasq

- name: DNSMasq | package
  tags:
  - package
  package:
    name: dnsmasq
    state: present

- name: DNSMasq | service
  tags:
  - service
  service:
    name: dnsmasq
    state: started
    enabled: yes
