---
- hosts: all
  become: true
  gather_facts: false

  tasks:

  - name: Syslog package
    action: apt pkg=sysklogd state=present

  - name: Syslog command line args
    action: file src=files/syslogd dest=/etc/default/syslogd
    notify:
    - Restart syslogd

  - name: Syslog config
    action: file src=files/syslog.conf dest=/etc/syslog.conf
    notify:
    - Restart syslogd

  - name: Syslog service
    action: service name=sysklogd state=started enabled=yes

  handlers:
  - name: Restart syslogd
    action: service name=sysklogd state=restarted
