---

- name: Node.js app | user
  tags:
    - user
  user:
    name: "{{ node_user }}"
    groups: "www-data"
    shell: /bin/false
    system: yes

- name: Node.js app | git clone
  tags:
    - package
    - git
  git:
    repo: "{{ node_repo }}"
    dest: "/home/{{ node_user }}/{{ node_name }}"
    depth: 1
  notify: restart node

- name: Node.js app | repo perms
  tags:
    - permissions
  file:
    path: "/home/{{ node_user }}/{{ node_name }}"
    owner: "{{ node_user }}"
    group: "{{ node_user }}"
    recurse: yes

- name: Node.js app | nginx host
  tags:
    - config
  template:
    src: node.nginx.j2
    dest: "/etc/nginx/sites-available/node-{{ node_name }}"
  notify: restart nginx

- name: Node.js app | enable nginx host
  tags:
    - config
  file:
    src: "/etc/nginx/sites-available/node-{{ node_name }}"
    dest: "/etc/nginx/sites-enabled/node-{{ node_name }}"
    state: link
  notify: restart nginx

- name: Node.js app | config dir
  tags:
    - dir
  file:
    path: "{{ node_config_dir }}"
    state: directory

- name: Node.js app | service config
  tags:
    - config
  template:
    src: "{{ item }}.j2"
    dest: "{{ node_config_dir }}/{{ item }}"
  with_items:
    - node.conf
  notify: restart node

- name: Node.js app | systemd service
  tags:
    - systemd
  copy:
    src: "{{ item }}"
    dest: /lib/systemd/system/
  with_items:
    - node.service
    - node@.service
  notify: restart node

- name: Node.js app | service
  tags:
    - service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - node
    - "node@{{ node_name }}"
