---

- name: Node.js app | user
  tags:
    - user
  user:
    name: "{{ node_user }}"
    groups: "www-data"
    shell: /bin/false
    system: yes

- name: Node.js app | git clone
  tags:
    - package
    - git
  git:
    repo: "{{ node_repo }}"
    dest: "/home/{{ node_user }}/{{ node_name }}"
    depth: 1
  notify: restart node-app

- name: Node.js app | repo perms
  tags:
    - permissions
  file:
    path: "/home/{{ node_user }}/{{ node_name }}"
    owner: "{{ node_user }}"
    group: "{{ node_user }}"
    recurse: yes

- name: Node.js app | nginx host
  tags:
    - config
  template:
    src: node.nginx.j2
    dest: "/etc/nginx/sites-available/node-{{ node_name }}"
  notify: restart nginx

- name: Node.js app | enable nginx host
  tags:
    - config
  file:
    src: "/etc/nginx/sites-available/node-{{ node_name }}"
    dest: "/etc/nginx/sites-enabled/node-{{ node_name }}"
    state: link
  notify: restart nginx

- name: Node.js app | systemd service
  tags:
    - systemd
  template:
    src: node.service.j2
    dest: "/etc/systemd/system/node-{{ node_name }}.service"
  notify: restart node-app

- name: Node.js app | refresh systemd
  systemd: daemon_reload=yes

- name: Node.js app | service
  tags:
    - service
  service:
    name: "node-{{ node_name }}"
    state: started
    enabled: true
