---

- name: PHP-FPM | packages
  tags:
  - package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - php-fpm
  - php-sqlite3
  - php-apcu

- name: PHP-FPM | config
  tags:
  - config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: nginx-php, dest: /etc/nginx/ }
  - { src: php.ini, dest: /etc/php/fpm/ }
  - { src: php-fpm.conf, dest: /etc/php/fpm/ }
  - { src: www.conf, dest: /etc/php/fpm/pool.d/ }
  notify: restart php-fpm

- name: PHP-FPM | service
  tags:
  - service
  service:
    name: php-fpm
    state: started
    enabled: yes
