---

- name: PostgreSQL | apt key
  tags:
  - apt
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"

- name: PostgreSQL | apt repo
  tags:
  - apt
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main'
    filename: 'postgresql.list'

- name: PostgreSQL | packages
  tags:
  - package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - "postgresql-{{ postgresql_version }}"
  - "postgresql-client-{{ postgresql_version }}"
  - libpq-dev
  - python-psycopg2

- name: PostgreSQL | config
  tags:
  - config
  copy:
    src: "{{ item }}"
    dest: /etc/postgresql/{{ postgresql_version }}/main/
    owner: postgres
    group: postgres
    mode: 0640
  with_items:
  - pg_hba.conf
  - postgresql.conf
  notify: restart postgresql

- name: PostgreSQL | backup cron job
  tags:
  - cron
  copy:
    src: pg_backup.cron
    dest: /etc/cron.daily/
    mode: 0750

- name: PostgreSQL | service
  tags:
  - service
  service:
    name: postgresql
    state: started
    enabled: yes

