---

- name: PostgreSQL | apt key
  tags:
  - apt
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"

- name: PostgreSQL | apt repo
  tags:
  - apt
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main'
    filename: 'postgresql'

- name: PostgreSQL | packages
  tags:
  - package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - "postgresql-{{ postgresql_version }}"
  - "postgresql-client-{{ postgresql_version }}"
  - libpq-dev
  - python-psycopg2

- name: PostgreSQL | config
  tags:
  - config
  template:
    src: "{{ item }}.j2"
    dest: "{{ postgresql_dir }}/{{ item }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: 0640
  with_items:
  - pg_hba.conf
  - postgresql.conf
  notify: restart postgresql

- name: PostgreSQL | backup cron
  tags:
  - cron
  cron:
    name: 'postgresql cron'
    cron_file: postgres
    minute: 18
    hour: 3
    user: "{{ postgresql_user }}"
    job: "/usr/bin/pg_dumpall -w | gzip -c --rsyncable > {{ postgresql_dump }}"

- name: PostgreSQL | service
  tags:
  - service
  service:
    name: postgresql
    state: started
    enabled: yes

