---

- name: journald | client | config
  tags:
    - config
  template:
    src: journal-upload.conf.j2
    dest: /etc/systemd/journal-upload.conf
  notify: 
    - restart journald
    - restart journal-upload

- name: journald | client | service file
  tags:
    - service
  copy:
    src: systemd-journal-upload.service
    dest: /etc/systemd/system/
  notify: 
    - restart journal-upload

- name: journald | client | service
  tags:
    - service
  service:
    name: systemd-journal-upload
    state: started
    enabled: yes
