---

- name: journald | remote | package
  tags:
    - package
    - systemd
  package:
    name: systemd-journal-remote
  notify: restart journal

- name: journald | dirs
  tags:
    - systemd
  file:
    path: /var/log/journal
    state: directory
    group: systemd-journal

- name: journald | service
  tags:
    - service
    - systemd
  service: 
    name: systemd-journald
    state: started
    enabled: yes
