---

- name: journald | server | socket config
  tags:
    - config
    - systemd
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - systemd-journal-remote.socket
  notify: restart journal-remote

- name: journald | server | storage dir
  tags:
    - systemd
  file:
    path: /var/log/journal/remote
    state: directory
    group: systemd-journal-remote

- name: journald | server | service
  tags:
    - service
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - systemd-journal-remote.service
    - systemd-journal-remote.socket
