---
# Add DNS entry in Cloudflare

- name: cloudflare | A record
  tags:
    - dns
  cloudflare_dns:
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_token }}"
    zone: "{{ cloudflare_zone }}"
    type: A
    record: "{{ inventory_hostname }}"
    value: "{{ ansible_host }}"

- name: cloudflare | CNAME
  tags:
    - dns
  cloudflare_dns:
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_token }}"
    zone: "{{ cloudflare_zone }}"
    type: CNAME
    record: "{{ item }}"
    value: "{{ inventory_hostname }}.{{ cloudflare_zone }}"
  with_items: "{{ cname }}"
